### ISSUE TITLE
Vte use raises exceptions

### ISSUE THREAD

**Issue by tony37** [sugarlabs/Snow#2]
Apparently this activity was converted to sugar3. However, Vte apparently has different methods than vte. 

Raises exception:

TypeError: argument foreground: Expected Gdk.RGBA, but got gi.overrides.Gdk.Color

after commenting out this line got 

AttributeError: 'Terminal' object has no attribute 'fork_command_full'.

**Comment by quozl** [comment]
Fixed by 7e4cac6d97adf5ed08304587fcb89648e239f2bb.
